begin;
select plan(45);

select has_table('public', 'order_amendments', 'order amendment proposals exist');
select has_table('public', 'refund_requests', 'offline refund requests exist');
select has_table('public', 'refund_confirmations', 'refund confirmations exist');
select ok((select relrowsecurity from pg_catalog.pg_class where oid = 'public.order_amendments'::regclass), 'amendments are protected by RLS');
select ok((select relrowsecurity from pg_catalog.pg_class where oid = 'public.refund_requests'::regclass), 'refund requests are protected by RLS');
select ok((select relrowsecurity from pg_catalog.pg_class where oid = 'public.refund_confirmations'::regclass), 'refund confirmations are protected by RLS');
select ok(exists (select 1 from pg_catalog.pg_index where indexrelid = 'order_amendments_active_uidx'::regclass), 'one active amendment per order');
select ok(exists (select 1 from pg_catalog.pg_index where indexrelid = 'refund_requests_active_uidx'::regclass), 'one active refund proposal per order');
select ok(exists (select 1 from pg_catalog.pg_constraint where conname = 'order_amendments_status'), 'amendment statuses are allowlisted');
select ok(exists (select 1 from pg_catalog.pg_constraint where conname = 'refund_requests_status'), 'refund statuses are allowlisted');
select ok(exists (select 1 from pg_catalog.pg_constraint where conname = 'refund_requests_basis'), 'refund bases are allowlisted');
select ok(exists (select 1 from pg_catalog.pg_constraint where conname = 'refund_requests_amount'), 'refund amounts are positive');
select ok(exists (select 1 from pg_catalog.pg_constraint where conname = 'refund_requests_parties'), 'refund payer and recipient differ');
select ok(exists (select 1 from pg_catalog.pg_constraint where conname = 'refund_confirmations_once'), 'refund receipt confirmation is one-time');
select ok(exists (select 1 from pg_catalog.pg_proc where proname = 'propose_order_amendment'), 'amendment proposal RPC exists');
select ok(exists (select 1 from pg_catalog.pg_proc where proname = 'accept_order_amendment'), 'amendment acceptance RPC exists');
select ok(exists (select 1 from pg_catalog.pg_proc where proname = 'reject_order_amendment'), 'amendment rejection RPC exists');
select ok(exists (select 1 from pg_catalog.pg_proc where proname = 'withdraw_order_amendment'), 'amendment withdrawal RPC exists');
select ok(exists (select 1 from pg_catalog.pg_proc where proname = 'propose_refund'), 'refund proposal RPC exists');
select ok(exists (select 1 from pg_catalog.pg_proc where proname = 'accept_refund'), 'refund acceptance RPC exists');
select ok(exists (select 1 from pg_catalog.pg_proc where proname = 'record_refund_sent'), 'refund sent RPC exists');
select ok(exists (select 1 from pg_catalog.pg_proc where proname = 'confirm_refund_received'), 'refund receipt RPC exists');
select ok(not has_table_privilege('authenticated', 'public.order_amendments', 'insert'), 'browser cannot insert amendments directly');
select ok(not has_table_privilege('authenticated', 'public.refund_requests', 'insert'), 'browser cannot insert refunds directly');
select ok(not has_table_privilege('authenticated', 'public.order_amendments', 'select'), 'browser reads amendments through DTO only');
select ok(not has_table_privilege('authenticated', 'public.refund_requests', 'select'), 'browser reads refund ledger through DTO only');
select ok(has_function_privilege('authenticated', 'public.propose_order_amendment(uuid,integer,jsonb,text,text,text,integer,timestamptz,text,uuid)', 'execute'), 'authenticated users can propose through RPC');
select ok(has_function_privilege('authenticated', 'public.accept_order_amendment(uuid,integer,uuid)', 'execute'), 'authenticated users can accept through RPC');
select ok(has_function_privilege('authenticated', 'public.propose_refund(uuid,integer,bigint,text,text,uuid)', 'execute'), 'authenticated users can propose refunds through RPC');
select ok(not has_function_privilege('anon', 'public.propose_refund(uuid,integer,bigint,text,text,uuid)', 'execute'), 'anonymous users cannot propose refunds');
select ok((select prosecdef from pg_catalog.pg_proc where oid = 'private.accept_order_amendment_command(uuid,integer,uuid)'::regprocedure), 'amendment acceptance runs server-side');
select ok((select prosecdef from pg_catalog.pg_proc where oid = 'private.propose_refund_command(uuid,integer,bigint,text,text,uuid)'::regprocedure), 'refund proposal runs server-side');
select ok(exists (select 1 from pg_catalog.pg_attribute where attrelid = 'public.order_amendments'::regclass and attname = 'base_revision'), 'amendment stores its base revision');
select ok(exists (select 1 from pg_catalog.pg_attribute where attrelid = 'public.order_amendments'::regclass and attname = 'proposed_revision'), 'amendment stores its proposed revision');
select ok(exists (select 1 from pg_catalog.pg_attribute where attrelid = 'public.refund_requests'::regclass and attname = 'policy_snapshot_ref'), 'refund policy basis is snapshotted');
select ok(exists (select 1 from pg_catalog.pg_attribute where attrelid = 'public.refund_requests'::regclass and attname = 'proof_note'), 'refund transfer evidence is optional and separate');
select ok(exists (select 1 from pg_catalog.pg_trigger where tgname = 'order_events_notification_insert'), 'amendment events use existing order notifications');
select ok(exists (select 1 from pg_catalog.pg_proc where proname = 'order_dto'), 'order DTO remains available after projections');
select ok((select prosecdef from pg_catalog.pg_proc where oid = 'private.confirm_refund_received_command(uuid,integer,uuid)'::regprocedure), 'refund confirmation is server-owned');
select ok((select provolatile = 'v' from pg_catalog.pg_proc where oid = 'public.accept_order_amendment(uuid,integer,uuid)'::regprocedure), 'amendment acceptance is volatile');
select ok((select provolatile = 'v' from pg_catalog.pg_proc where oid = 'public.confirm_refund_received(uuid,integer,uuid)'::regprocedure), 'refund confirmation is volatile');
select ok(not exists (select 1 from pg_catalog.pg_attribute where attrelid = 'public.refund_requests'::regclass and attname in ('gateway_payment_id', 'platform_balance')), 'refund ledger does not pretend to hold money');
select ok(exists (select 1 from pg_catalog.pg_proc where proname = 'order_refund_cap'), 'refund cap is calculated server-side');
select ok(exists (select 1 from pg_catalog.pg_attribute where attrelid = 'public.refund_confirmations'::regclass and attname = 'confirmed_by'), 'recipient confirmation actor is recorded');
select ok(exists (select 1 from pg_catalog.pg_attribute where attrelid = 'public.refund_confirmations'::regclass and attname = 'confirmed_at'), 'recipient confirmation time is recorded');
select * from finish();
rollback;
