begin;
select plan(35);

select has_table('private', 'product_events', 'product event table exists');
select has_table('private', 'user_activity_days', 'activity day table exists');
select has_table('private', 'listing_visibility_periods', 'listing visibility periods exist');
select has_table('private', 'metric_rollups', 'metric rollup table exists');
select ok((select relrowsecurity from pg_catalog.pg_class where oid = 'private.product_events'::regclass), 'product events are protected by RLS');
select ok((select relrowsecurity from pg_catalog.pg_class where oid = 'private.user_activity_days'::regclass), 'activity days are protected by RLS');
select ok((select relrowsecurity from pg_catalog.pg_class where oid = 'private.listing_visibility_periods'::regclass), 'visibility periods are protected by RLS');
select ok(exists (select 1 from pg_catalog.pg_constraint where conname = 'product_events_type'), 'event types are allowlisted');
select ok(exists (select 1 from pg_catalog.pg_constraint where conname = 'product_events_attributes'), 'event attributes are objects');
select ok(exists (select 1 from pg_catalog.pg_constraint where conname = 'product_events_source_key'), 'events have bounded dedupe keys');
select ok(exists (select 1 from pg_catalog.pg_constraint where conname = 'product_events_source_key_key'), 'events deduplicate by source key');
select ok(exists (select 1 from pg_catalog.pg_index where indexrelid = 'listing_visibility_periods_open_uidx'::regclass), 'only one open visibility period exists per listing');
select ok(exists (select 1 from pg_catalog.pg_proc where proname = 'record_product_event'), 'event recorder exists');
select ok(exists (select 1 from pg_catalog.pg_proc where proname = 'get_product_metrics'), 'admin metrics RPC exists');
select ok(not has_function_privilege('anon', 'public.get_product_metrics(date, date)', 'execute'), 'anonymous users cannot read metrics');
select ok(has_function_privilege('authenticated', 'public.get_product_metrics(date, date)', 'execute'), 'authenticated role can reach admin-gated metrics RPC');
select ok(exists (select 1 from pg_catalog.pg_trigger where tgname = 'account_state_analytics_event'), 'completed onboarding emits an event');
select ok(exists (select 1 from pg_catalog.pg_trigger where tgname = 'listings_analytics_visibility'), 'listing visibility is tracked');
select ok(exists (select 1 from pg_catalog.pg_trigger where tgname = 'messages_analytics_event'), 'messages emit activity events');
select ok(exists (select 1 from pg_catalog.pg_trigger where tgname = 'transaction_events_analytics_event'), 'completed barter emits an event');
select ok(exists (select 1 from pg_catalog.pg_trigger where tgname = 'orders_analytics_completion'), 'completed orders emit an event');
select ok(exists (select 1 from pg_catalog.pg_trigger where tgname = 'stores_analytics_event'), 'store activation emits an event');
select ok(exists (select 1 from pg_catalog.pg_trigger where tgname = 'subscriptions_analytics_event'), 'Plus activation emits an event');
select ok(not has_table_privilege('authenticated', 'private.product_events', 'select'), 'authenticated users cannot inspect raw event payloads');
select ok(not has_table_privilege('authenticated', 'private.user_activity_days', 'select'), 'authenticated users cannot inspect activity cohorts');
select ok(not has_table_privilege('authenticated', 'private.metric_rollups', 'select'), 'authenticated users cannot inspect rollups directly');
select ok((select prosecdef from pg_catalog.pg_proc where oid = 'private.record_product_event(text,text,uuid,uuid,text,timestamptz,jsonb)'::regprocedure), 'event recorder runs with server privileges');
select ok((select prosecdef from pg_catalog.pg_proc where oid = 'public.get_product_metrics(date,date)'::regprocedure), 'metrics RPC runs with server privileges after admin check');
select ok((select provolatile = 'v' from pg_catalog.pg_proc where oid = 'public.get_product_metrics(date,date)'::regprocedure), 'metrics RPC is volatile because it reads a live window');
select ok(exists (select 1 from pg_catalog.pg_attribute where attrelid = 'private.product_events'::regclass and attname = 'is_test'), 'events can separate test data');
select ok(exists (select 1 from pg_catalog.pg_attribute where attrelid = 'private.product_events'::regclass and attname = 'attributes_allowlist'), 'event payload uses an allowlist field');
select ok(exists (select 1 from pg_catalog.pg_attribute where attrelid = 'private.user_activity_days'::regclass and attname = 'activity_date'), 'retention is based on activity days');
select ok(exists (select 1 from pg_catalog.pg_attribute where attrelid = 'private.listing_visibility_periods'::regclass and attname = 'ended_at'), 'listing visibility periods can close');
select ok(exists (select 1 from pg_catalog.pg_attribute where attrelid = 'private.metric_rollups'::regclass and attname = 'dimensions'), 'rollups support aggregate dimensions');
select ok(not exists (select 1 from pg_catalog.pg_attribute where attrelid = 'private.product_events'::regclass and attname in ('phone', 'address', 'message_body')), 'raw PII and message content are excluded from event storage');
select * from finish();
rollback;
