import { useEffect, useState, type FormEvent } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { StatusPanel } from '../../components/StatusPanel';
import { PageHeading } from '../../components/SurfacePrimitives';
import { useOrderGateway } from './OrderContext';

export function OrderAmendmentPage() {
  const { id = '' } = useParams(); const gateway = useOrderGateway(); const navigate = useNavigate();
  const query = useQuery({ queryKey: ['order', id], queryFn: () => gateway!.get(id), enabled: Boolean(gateway && id) });
  const room = query.data; const item = room?.items[0]; const [hydrated, setHydrated] = useState(false);
  const [quantity, setQuantity] = useState(() => String(item?.quantity ?? 1)); const [method, setMethod] = useState<'pickup' | 'meetup' | 'delivery'>(() => room?.terms.handoverMethod ?? 'meetup'); const [note, setNote] = useState(() => room?.terms.handoverNote ?? ''); const [shipping, setShipping] = useState(() => room?.terms.shippingAmountRupiah ?? '0'); const [dpPercent, setDpPercent] = useState(() => String(room?.terms.dpPercent ?? 0)); const [deadline, setDeadline] = useState(() => room?.terms.dpDeadline ? room.terms.dpDeadline.slice(0, 16) : ''); const [reason, setReason] = useState('');
  useEffect(() => { if (!room || hydrated) return; setQuantity(String(room.items[0]?.quantity ?? 1)); setMethod(room.terms.handoverMethod); setNote(room.terms.handoverNote); setShipping(room.terms.shippingAmountRupiah); setDpPercent(String(room.terms.dpPercent)); setDeadline(room.terms.dpDeadline ? room.terms.dpDeadline.slice(0, 16) : ''); setHydrated(true); }, [hydrated, room]);
  const mutation = useMutation({ mutationFn: () => gateway!.proposeAmendment(id, room!.acceptedRevision ?? room!.revision, [{ variantId: item?.variantId ?? undefined, quantity }], { handoverMethod: method, handoverNote: note, shippingAmountRupiah: shipping, dpPercent: Number(dpPercent), dpDeadline: deadline ? new Date(deadline).toISOString() : null, reason: reason.trim() }, crypto.randomUUID()), onSuccess: () => navigate(`/orders/${id}`) });
  if (!gateway) return <StatusPanel title="Amendment belum aktif"><p>Hubungkan backend untuk mengubah pesanan.</p></StatusPanel>;
  if (query.isPending) return <StatusPanel title="Memuat pesanan…" />;
  if (query.error || !room) return <StatusPanel title="Pesanan tidak tersedia" error />;
  if (room.actorRole !== 'seller' || !['confirmed', 'awaiting_dp'].includes(room.lifecycle)) return <StatusPanel title="Amendment belum tersedia"><p>Perubahan hanya dapat diusulkan penjual sebelum pesanan mulai diproses.</p><Link to={`/orders/${id}`}>Kembali ke pesanan</Link></StatusPanel>;
  function submit(event: FormEvent) { event.preventDefault(); if (!item || Number(quantity) < 1 || !Number.isInteger(Number(quantity)) || !reason.trim() || Number(dpPercent) < 0 || Number(dpPercent) > 100) return; mutation.mutate(); }
  return <section className="order-editor"><PageHeading leading={<Link className="back-link" to={`/orders/${id}`}>Kembali ke pesanan</Link>} kicker={`Proposal revisi · Versi ${room.revision}`} title="Usulkan perubahan pesanan" description="Versi lama tetap tersimpan. Pesanan tidak berubah sampai pembeli menyetujui proposal ini." /><section className="revision-warning"><strong>Pembayaran tetap langsung antar pihak.</strong><p>Barter tidak menerima, menahan, atau memindahkan uang. Nominal DP hanya menjadi bagian dari snapshot kesepakatan.</p></section><form className="stack-form" onSubmit={submit}><label>Barang<input value={item?.name ?? ''} readOnly /></label><label>Jumlah<input aria-label="Jumlah" inputMode="numeric" value={quantity} onChange={event => setQuantity(event.target.value.replace(/\D/g, ''))} /></label><label>Cara penyerahan<select value={method} onChange={event => setMethod(event.target.value as typeof method)}><option value="pickup">Diambil</option><option value="meetup">Bertemu</option><option value="delivery">Diantar</option></select></label><label>Catatan penyerahan<textarea rows={3} value={note} onChange={event => setNote(event.target.value)} maxLength={500} /></label><label>Ongkir<input inputMode="numeric" value={shipping} onChange={event => setShipping(event.target.value.replace(/\D/g, '') || '0')} /></label><label>DP (%)<input inputMode="numeric" value={dpPercent} onChange={event => setDpPercent(event.target.value.replace(/\D/g, '').slice(0, 3))} /></label><label>Tenggat DP <span className="optional">(opsional)</span><input type="datetime-local" value={deadline} onChange={event => setDeadline(event.target.value)} /></label><label>Alasan perubahan<textarea aria-label="Alasan perubahan" rows={4} minLength={2} maxLength={300} value={reason} onChange={event => setReason(event.target.value)} placeholder="Contoh: jumlah pesanan berubah" /></label>{(mutation.error || (reason.length > 0 && reason.trim().length < 2)) && <p className="form-alert" role="alert">Usulan belum tersimpan. Lengkapi alasan dan periksa kembali detailnya.</p>}<button className="button" type="submit" disabled={mutation.isPending || !reason.trim() || !item}>{mutation.isPending ? 'Mengirim…' : 'Kirim usulan perubahan'}</button></form></section>;
}
