import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { StatusPanel } from '../../components/StatusPanel';
import { formatRupiah } from '../../lib/money';
import { useOrderGateway } from './OrderContext';

export function RefundPage() {
  const { id = '' } = useParams(); const gateway = useOrderGateway(); const client = useQueryClient();
  const query = useQuery({ queryKey: ['order', id], queryFn: () => gateway!.get(id), enabled: Boolean(gateway && id) }); const room = query.data;
  const [amount, setAmount] = useState(() => room?.settlement?.refundCapRupiah ?? '0'); const [reason, setReason] = useState(''); const [proof, setProof] = useState('');
  useEffect(() => { if (room?.settlement?.refundCapRupiah && amount === '0') setAmount(room.settlement.refundCapRupiah); }, [amount, room?.settlement?.refundCapRupiah]);
  const active = room?.refunds?.find(refund => ['proposed', 'accepted', 'sent_unconfirmed'].includes(refund.status));
  const run = useMutation({ mutationFn: async (action: string) => { const revision = room!.acceptedRevision ?? room!.revision; const key = crypto.randomUUID(); if (action === 'propose') return gateway!.proposeRefund(id, revision, amount, reason.trim(), 'cancellation', key); if (action === 'accept') return gateway!.acceptRefund(active!.id, revision, key); if (action === 'reject') return gateway!.rejectRefund(active!.id, revision, key); if (action === 'sent') return gateway!.recordRefundSent(active!.id, revision, proof.trim(), key); return gateway!.confirmRefundReceived(active!.id, revision, key); }, onSuccess: data => { client.setQueryData(['order', id], data); setReason(''); setProof(''); } });
  if (!gateway) return <StatusPanel title="Refund belum aktif"><p>Hubungkan backend untuk melihat tindak lanjut refund.</p></StatusPanel>;
  if (query.isPending) return <StatusPanel title="Memuat tindak lanjut pembayaran…" />;
  if (query.error || !room) return <StatusPanel title="Pesanan tidak tersedia" error />;
  const cap = room.settlement?.refundCapRupiah ?? '0';
  const canPropose = room.actorRole === 'seller' && room.lifecycle === 'cancelled' && Number(cap) > 0;
  return <section className="order-editor"><Link className="back-link" to={`/orders/${id}`}>Kembali ke pesanan</Link><header><p className="eyebrow">Tindak lanjut manual</p><h1>Pengembalian dana langsung</h1><p>Barter tidak menerima atau memindahkan uang. Halaman ini hanya mencatat kesepakatan dan konfirmasi antar pihak.</p></header><section className="simulation-warning"><strong>Maksimal {formatRupiah(cap)}</strong><p>Nominal maksimal dihitung dari pembayaran yang sudah dikonfirmasi penjual, dikurangi refund yang sudah diterima. Transfer tetap dilakukan di luar Barter.</p></section>{active ? <section className="trade-package"><h2>Status refund</h2><p>{formatRupiah(active.amountRupiah)} · {active.status}</p><p>{active.reason}</p>{active.status === 'proposed' && room.actorRole === 'buyer' && <div className="form-actions"><button className="button" disabled={run.isPending} onClick={() => run.mutate('accept')}>Setujui nominal</button><button className="button secondary" disabled={run.isPending} onClick={() => run.mutate('reject')}>Tolak</button></div>}{active.status === 'accepted' && room.actorRole === 'seller' && <div className="stack-form"><label>Bukti/catatan transfer (opsional)<textarea rows={3} maxLength={1000} value={proof} onChange={event => setProof(event.target.value)} /></label><button className="button" disabled={run.isPending} onClick={() => run.mutate('sent')}>Tandai transfer terkirim</button></div>}{active.status === 'sent_unconfirmed' && room.actorRole === 'buyer' && <button className="button" disabled={run.isPending} onClick={() => run.mutate('received')}>Konfirmasi dana diterima</button>}</section> : canPropose ? <form className="stack-form" onSubmit={event => { event.preventDefault(); if (Number(amount) > 0 && Number(amount) <= Number(cap) && reason.trim().length >= 5) run.mutate('propose'); }}><label>Nominal refund<input inputMode="numeric" value={amount} onChange={event => setAmount(event.target.value.replace(/\D/g, ''))} /></label><label>Alasan<textarea rows={4} minLength={5} maxLength={1000} value={reason} onChange={event => setReason(event.target.value)} /></label><button className="button" disabled={run.isPending || Number(amount) <= 0 || Number(amount) > Number(cap) || reason.trim().length < 5}>Ajukan refund</button></form> : <StatusPanel title="Belum ada refund aktif"><p>Refund hanya dapat dicatat setelah pembatalan atau keputusan admin dan pembayaran yang sudah dikonfirmasi.</p></StatusPanel>}{run.error && <p className="form-alert" role="alert">Tindakan refund belum tersimpan. Periksa status terbaru sebelum mencoba lagi.</p>}</section>;
}
