import { useState, type FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { StatusPanel } from '../../components/StatusPanel';
import { useAdminGateway } from './AdminContext';
import type { ReportOutcome } from './types';

const outcomes: Array<[ReportOutcome, string]> = [['no_action', 'Tidak ada tindakan'], ['return_required', 'Minta pengembalian barang'], ['cancel_transaction', 'Batalkan transaksi melalui keputusan admin'], ['admin_complete', 'Tandai selesai melalui keputusan admin'], ['restrict_account', 'Batasi akun'], ['ban_account', 'Ban akun']];
export function AdminReportDetailPage() {
  const { id = '' } = useParams(); const gateway = useAdminGateway(); const client = useQueryClient();
  const query = useQuery({ queryKey: ['admin-report', id], queryFn: () => gateway!.getReport(id), enabled: Boolean(gateway && id) });
  const [outcome, setOutcome] = useState<ReportOutcome>('no_action'); const [rationale, setRationale] = useState(''); const [actionUserId, setActionUserId] = useState(''); const [durationDays, setDurationDays] = useState('30'); const [error, setError] = useState<string | null>(null);
  const decide = useMutation({ mutationFn: () => gateway!.decide(id, query.data?.decisionVersion ?? 1, { outcome, rationale: rationale.trim(), actionUserId: outcome === 'restrict_account' || outcome === 'ban_account' ? actionUserId.trim() || null : null, sanctionKind: outcome === 'restrict_account' ? 'restriction' : outcome === 'ban_account' ? 'ban' : null, durationDays: outcome === 'restrict_account' || outcome === 'ban_account' ? Number(durationDays) : null }), onSuccess: data => { client.setQueryData(['admin-report', id], data); setError(null); } });
  function submit(event: FormEvent) { event.preventDefault(); if (rationale.trim().length < 10) { setError('Alasan keputusan minimal 10 karakter.'); return; } if ((outcome === 'restrict_account' || outcome === 'ban_account') && !actionUserId.trim()) { setError('Masukkan ID akun yang dikenai sanksi; server tetap memvalidasi bahwa akun terkait kasus.'); return; } setError(null); decide.mutate(); }
  if (!gateway) return <StatusPanel title="Panel admin belum aktif"><p>Hubungkan backend dengan role admin.</p></StatusPanel>;
  if (query.isPending) return <StatusPanel title="Memuat laporan…" />;
  if (query.error || !query.data) return <StatusPanel title="Laporan tidak tersedia" error><Link to="/admin/reports">Kembali ke antrean</Link></StatusPanel>;
  const report = query.data; const canDecide = report.status === 'open' || report.status === 'under_review';
  return <section className="admin-report-detail"><Link className="back-link" to="/admin/reports">Kembali ke antrean</Link><header><p className="eyebrow">Kasus {report.id.slice(0, 8)}</p><h1>{report.context.title}</h1><p>Status: {report.status} · dilaporkan oleh {report.reporter.name}</p></header><section className="case-context"><h2>Konteks terbatas</h2><p>{report.context.summary}</p><p><strong>Jenis:</strong> {report.targetType}</p><p><strong>Alasan:</strong> {report.reason}</p><p>{report.description}</p>{report.evidence?.length ? <><h3>Bukti yang dilampirkan</h3><ul>{report.evidence.map((evidence: NonNullable<typeof report.evidence>[number]) => <li key={evidence.id}>{evidence.sourceType} · {evidence.note || 'Tanpa catatan'}</li>)}</ul></> : <p className="metadata">Belum ada bukti terstruktur yang dilampirkan.</p>}</section>{report.decision && <section className="case-context"><h2>Keputusan terakhir</h2><p><strong>{report.decision.outcome}</strong> · {report.decision.rationale}</p></section>}{canDecide ? <form className="stack-form" onSubmit={submit}><h2>Catat keputusan</h2><label>Outcome<select value={outcome} onChange={event => setOutcome(event.target.value as ReportOutcome)}>{outcomes.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{(outcome === 'restrict_account' || outcome === 'ban_account') && <><label>ID akun yang dikenai sanksi<input value={actionUserId} onChange={event => setActionUserId(event.target.value)} placeholder="UUID peserta yang terbukti melanggar" /></label><label>Durasi hari<input inputMode="numeric" value={durationDays} onChange={event => setDurationDays(event.target.value.replace(/\D/g, ''))} /></label></>}<label>Alasan keputusan<textarea rows={6} maxLength={3000} value={rationale} onChange={event => setRationale(event.target.value)} /></label>{(error || decide.error) && <p className="form-alert" role="alert">{error ?? 'Keputusan belum tersimpan. Versi kasus mungkin sudah berubah; muat ulang.'}</p>}<button className="button" type="submit" disabled={decide.isPending}>{decide.isPending ? 'Menyimpan keputusan…' : 'Simpan keputusan'}</button></form> : <p className="success-notice">Kasus ini sudah diputuskan. Keputusan bersifat audit dan tidak menulis penerimaan barang atau pembayaran atas nama pengguna.</p>}</section>;
}
