import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { StatusPanel } from '../../components/StatusPanel';
import { useStoreGateway } from './StoreContext';
import type { StoreInput } from './types';

export function MyStoresPage() {
  const gateway = useStoreGateway(); const client = useQueryClient(); const [input, setInput] = useState<StoreInput>({ slug: '', name: '', description: '', category: 'Makanan', areaId: 'jabodetabek', areaLabel: 'Jabodetabek', operatingHours: '', handoverMethods: ['meetup'], publicAddress: '', publicAddressConsent: false }); const [error, setError] = useState<string | null>(null);
  const stores = useQuery({ queryKey: ['stores', 'mine'], queryFn: () => gateway!.getMyStores(), enabled: Boolean(gateway) });
  const create = useMutation({ mutationFn: () => gateway!.createStore(input), onSuccess: () => { setInput(current => ({ ...current, slug: '', name: '', description: '' })); void client.invalidateQueries({ queryKey: ['stores', 'mine'] }); } });
  function change(key: keyof StoreInput, value: string | boolean) { setInput(current => ({ ...current, [key]: value })); }
  function submit(event: React.FormEvent) { event.preventDefault(); if (!/^[a-z0-9](?:[a-z0-9-]{1,48}[a-z0-9])?$/.test(input.slug) || input.name.trim().length < 2 || input.category.trim().length < 2) { setError('Slug, nama toko, dan kategori wajib diisi. Gunakan slug huruf kecil.'); return; } setError(null); create.mutate(); }
  if (!gateway) return <StatusPanel title="Toko belum aktif"><p>Aktifkan backend dan Plus untuk mengelola toko.</p></StatusPanel>;
  if (stores.isPending) return <StatusPanel title="Memuat toko…" />;
  if (stores.error) return <StatusPanel title="Toko belum dapat dimuat" error><button className="button" onClick={() => void stores.refetch()}>Coba lagi</button></StatusPanel>;
  return <section className="stores-page"><header><p className="eyebrow">Toko saya</p><h1>Profil usaha</h1><p>Satu akun dapat memiliki sampai tiga toko Plus. Produk tetap dikelola lewat listing.</p></header>{stores.data?.length ? <div className="owner-list">{stores.data.map(store => <article key={store.id}><div><span className="label">{store.status === 'active' ? 'Aktif' : 'Tersembunyi'}</span><h2>{store.name}</h2><p>barter.app/stores/{store.slug} · {store.category} · {store.areaLabel}</p></div><Link className="button secondary" to={`/stores/${store.slug}`}>Lihat profil</Link></article>)}</div> : <StatusPanel title="Belum ada toko"><p>Tambahkan profil untuk usaha catering, PO, atau produk preloved.</p></StatusPanel>}<form className="stack-form plus-panel" onSubmit={submit}><h2>Buat toko baru</h2><label>Slug publik<input value={input.slug} onChange={event => change('slug', event.target.value.toLowerCase())} placeholder="dapur-rina" /></label><label>Nama toko<input value={input.name} onChange={event => change('name', event.target.value)} /></label><label>Kategori usaha<input value={input.category} onChange={event => change('category', event.target.value)} /></label><label>Deskripsi<textarea rows={3} maxLength={2000} value={input.description} onChange={event => change('description', event.target.value)} /></label><label>Jam operasional<input value={input.operatingHours} onChange={event => change('operatingHours', event.target.value)} placeholder="Senin–Sabtu, 08.00–17.00" /></label><label>Alamat publik (opsional)<textarea rows={2} value={input.publicAddress} onChange={event => change('publicAddress', event.target.value)} /></label><label className="check-row"><input type="checkbox" checked={input.publicAddressConsent} onChange={event => change('publicAddressConsent', event.target.checked)} />Tampilkan alamat ini di profil toko</label>{(error || create.error) && <p className="form-alert" role="alert">{error ?? 'Toko belum tersimpan. Coba lagi.'}</p>}<button className="button" disabled={create.isPending}>{create.isPending ? 'Membuat toko…' : 'Buat toko'}</button></form></section>;
}
